// words.js
const ENGLISH_WORDS = [
    "ABANDON", "ABILITY", "ABSENCE", "ACADEMY", "ACCOUNT", "ACCUSED", "ACHIEVE", "ACQUIRE", "ADDRESS", "ADAPTED",
    "ADVANCE", "ADVISOR", "AIRPORT", "ALCOHOL", "ALREADY", "AMATEUR", "AMAZING", "ANALYZE", "ANCIENT", "ANGELIC",
    "ANIMALS", "ANOTHER", "ANXIETY", "ANYBODY", "APOLLO", "APPEALS", "APPOINT", "APPROVE", "ARCHERY", "ARCHITECTURE",
    "ARRANGE", "ARTISTS", "ASPECTS", "ASSAULT", "ASSUMED", "ATHLETE", "ATTEMPT", "ATTRACT", "AUCTION", "AVERAGE",
    "BALANCE", "BALLOON", "BANKING", "BARRIER", "BATTERY", "BECAUSE", "BEDROOM", "BELIEVE", "BENEATH", "BENEFIT",
    "BETWEEN", "BILLION", "BIOLOGY", "BLANKET", "BLOCKS", "BOATING", "BOTTLES", "BOUNDARY", "BRAVERY", "BREAKS",
    "BRIDGE", "BRIGHT", "BROTHER", "BROWSER", "BUDGET", "BUILDER", "BURNING", "BUSINESS", "BUTTONS", "CABINET",
    "CAMERA", "CAMPING", "CAPITAL", "CAPTAIN", "CAPTURE", "CARAVAN", "CARRIER", "CARTOON", "CASTING", "CATALOG",
    "CAUTION", "CEILING", "CENTRAL", "CENTURY", "CHAMBER", "CHANNEL", "CHAPTER", "CHARITY", "CHARLIE", "CHICKEN",
    "CHIMNEY", "CHOICES", "CHRONIC", "CIRCUIT", "CLASSES", "CLASSIC", "CLEANER", "CLIMATE", "CLOSURE", "CLOTHES",
    "COACHES", "COASTAL", "COFFEE", "COLLECT", "COLLEGE", "COLUMNS", "COMBINE", "COMFORT", "COMMAND", "COMMENT",
    "COMPACT", "COMPANY", "COMPARE", "COMPLEX", "CONCEPT", "CONCERN", "CONCERT", "CONDUCT", "CONFIRM", "CONNECT",
    "CONSENT", "CONSIST", "CONTACT", "CONTAIN", "CONTENT", "CONTEST", "CONTEXT", "CONTROL", "CONVERT", "COOKING",
    "COUNCIL", "COUNTER", "COUNTRY", "COUPLED", "COURSES", "COUSINS", "COVERED", "CRAFTED", "CREATES", "CREATURE",
    "CREDITS", "CRICKET", "CRITICAL", "CRYSTAL", "CULTURE", "CURRENT", "CUTTING", "DANCING", "DANGEROUS", "DATASET",
    "DEALERS", "DEBATES", "DECADES", "DECIMAL", "DECLARE", "DECLINE", "DEFAULT", "DEFENSE", "DEFINED", "DELIVER",
    "DENSITY", "DEPOSIT", "DESKTOP", "DESPITE", "DESTINY", "DESTROY", "DETAILS", "DEVELOP", "DEVICES", "DIAGRAM",
    "DIAMOND", "DIGITAL", "DIGNITY", "DINNERS", "DIRECTS", "DISABLE", "DISPLAY", "DISTANT", "DIVIDED", "DIVORCE",
    "DOCTORS", "DOPHINS", "DRAWING", "DREAMS", "DRIVING", "DYNAMIC", "EARLIER", "EASTERN", "ECONOMY", "EDITION",
    "EFFECTS", "EFFORTS", "EIGHTH", "ELEMENT", "EMOTION", "EMPIRE", "EMPLOY", "EMPTY", "ENABLED", "ENEMIES",
    "ENERGY", "ENGAGED", "ENGINE", "ENGLISH", "ENHANCE", "ENJOYED", "ENORMOUS", "ENQUIRY", "ENSURES", "ENTIRELY",
    "ENTRIES", "EPISODE", "EQUALLY", "EQUATED", "EQUIPED", "ESCAPED", "ESSENCE", "EVENING", "EVIDENT", "EXACTLY",
    "EXAMINE", "EXAMPLE", "EXCITED", "EXCLUDE", "EXHIBIT", "EXISTED", "EXPERTS", "EXPLAIN", "EXPLORE", "EXPRESS",
    "EXTRACT", "EXTREME", "FACTORY", "FACULTY", "FAILURE", "FAIRLY", "FAITH", "FALLING", "FAMILIES", "FANTASY",
    "FARMERS", "FASHION", "FEATURE", "FEDERAL", "FEELING", "FICTION", "FIFTEEN", "FIGHTER", "FINALLY", "FINANCE",
    "FINDING", "FINGERS", "FIREMAN", "FISHING", "FITNESS", "FLIGHTS", "FLOWERS", "FOCUSING", "FOLDING", "FOLLOWS",
    "FOOTAGE", "FOREIGN", "FOREVER", "FORMULA", "FORTUNE", "FORWARD", "FOUNDER", "FREEDOM", "FREQUENT", "FRIENDS",
    "FUNDING", "FUNERAL", "GALLERY", "GALAXY", "GARDEN", "GENERAL", "GENETIC", "GENUINE", "GESTURE", "GHOSTS",
    "GIANTS", "GIFTED", "GLASSES", "GLOBAL", "GODDESS", "GOLDEN", "GOODBYE", "GOVERN", "GRADUAL", "GRAMMAR",
    "GRAPHIC", "GREATER", "GROUPS", "GROWING", "GUARDS", "GUESSED", "GUITAR", "HABITAT", "HANDLED", "HAPPILY",
    "HARBOR", "HARDWARE", "HARVEST", "HEALTHY", "HEARING", "HEAVEN", "HEIGHTS", "HELPFUL", "HEROES", "HISTORY",
    // --- Nature & Space ---
    "GALAXY", "PLANET", "STARS", "METEOR", "COMET", "NEBULA", "ORBIT", "ROCKET", "SPACESHIP", "SOLAR",
    "OCEAN", "FOREST", "DESERT", "VALLEY", "ISLAND", "CANARY", "RIVER", "VOLCANO", "STORM", "THUNDER",
    "BREEZE", "JUNGLE", "CANYON", "GLACIER", "QUAKE", "SPRING", "SUMMER", "AUTUMN", "WINTER", "SUNSET",
    // --- Technology & Digital ---
    "CODING", "GITHUB", "PYTHON", "MOBILE", "LAPTOP", "SCREEN", "MODEM", "ROUTER", "SERVER", "BACKUP",
    "PIXEL", "BROWSER", "WIDGET", "GADGET", "RELOAD", "UPDATE", "ENGINE", "SYSTEM", "STORAGE", "MEMORY",
    "HACKER", "ONLINE", "SIGNAL", "CHIPSET", "KEYBOARD", "DISPLAY", "CONSOLE", "NETWORK", "VIRTUAL", "DIGITAL",
    // --- Objects & Home ---
    "MIRROR", "WINDOW", "BASKET", "KITCHEN", "BEDROOM", "CHIMNEY", "CURTAIN", "PILLOW", "BLANKET", "HAMMER",
    "GUITAR", "CAMERA", "BOTTLE", "LANTERN", "CANDLE", "CLOCK", "WATCH", "WALLET", "JACKET", "GLOVES",
    "HAMMER", "PENCIL", "ERASER", "NOTEBOOK", "CABINET", "TEAPOT", "FRIDGE", "STOVE", "HEATER", "TABLET",
    // --- Animals ---
    "TIGER", "LEOPARD", "GIRAFFE", "MONKEY", "RABBIT", "DOLPHIN", "SHARK", "WHALE", "PENGUIN", "EAGLE",
    "FALCON", "PARROT", "TURTLE", "LIZARD", "SPIDER", "BEETLE", "BUTTERFLY", "DRAGON", "PHOENIX", "PANTHER",
    // --- Jobs & Professions ---
    "DOCTOR", "LAWYER", "POLICE", "ARTIST", "WRITER", "SINGER", "DANCER", "PILOT", "SAILOR", "CHEF",
    "FARMER", "COACH", "JUDGE", "NURSE", "DESIGNER", "ARCHER", "BUILDER", "DRIVER", "PLAYER", "TEACHER",
    // --- Abstract & Feelings ---
    "SUCCESS", "VICTORY", "FREEDOM", "BRAVERY", "HONESTY", "LOYALTY", "WISDOM", "ENERGY", "SILENCE", "DREAMS",
    "SMILING", "FRIENDS", "COUSINS", "BROTHER", "SISTER", "PARENTS", "HEALTHY", "STRONG", "SMART", "ACTIVE",
    // --- Sports & Fun ---
    "SOCCER", "TENNIS", "HOCKEY", "CHESS", "BOXING", "SKATING", "SURFING", "DIVING", "RACING", "ARCHERY",
    "STADIUM", "TROPHY", "WINNER", "CHAMPION", "OLYMPIC", "PUZZLE", "CARTOON", "MOVIE", "CINEMA", "CONCERT",
    // --- Transportation ---
    "AIRPLANE", "ROCKET", "SUBWAY", "TRAIN", "BICYCLE", "SCOOTER", "TRUCK", "TAXICAB", "STATION", "AIRPORT",
    // --- Food & Drinks ---
    "CHERRY", "BANANA", "ORANGE", "PEACHES", "COFFEE", "BURGER", "PIZZAS", "COOKIES", "CHEESE", "YOGURT"
];